### ISSUE TITLE
Precision issue with numbers greater than 100,000,000,000,000,000

### ISSUE THREAD

**Issue by labithiotis** [KaiHotz/React-Calculator-App#1]
Entering `100,000,000,000,000,000` then plus(+) `56` results in `100,000,000,000,000,000`

Expected `100,000,000,000,000,056`

**Comment by KaiHotz** [comment]
This has to do with Javascript's numeric precision. There's probably no way to overcome this using Javascript, since the highest safe integer in JS is 9,007,199,254,740,991.
